### DISCUSSION TITLE
Question about docker usage with Caddy

### DISCUSSION THREAD

**Discussion by spencerflagg** [ohmyform/ohmyform#166] [Q&A] [answered]
#### What's this issue about?

_(bit of a Docker newb - sorry. I hope this is the right place to post questions. I've been spinning my wheels on this, trying different permutations none of which have worked, and figured I'd reach out to the community for insight.)_

I'm trying to incorporate OhMyForm into an existing `docker-compose.yml` that uses Caddy and docker networks.

Any suggestions for how I can adjust OhMyForm's compose for integrating with the below would be greatly appreciated.

Thanks in advance!

**docker-compose.yml**
```
version: "3.9"

networks:
        web:
                external: true
        internal:
                external: false
                driver: bridge

services:
        caddy:
                container_name: caddy
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
                        - /data/caddy/data:/data # Optional
                        - /data/caddy/config:/config # Optional
                networks:
                        - web
                        - internal
        ghost-alt:
                container_name: ghost-alt
                image: ghost:4-alpine
                restart: unless-stopped
                environment:
                        - url=https://mydomain.com # Change to your domain
                volumes:
                        - /data/ghost-alt:/var/lib/ghost/content
                networks:
                        - internal
```

**Caddyfile**
```
mydomain.com {
    reverse_proxy ghost-alt:2368
}
```

**Comment by wodka** [comment]
probably best to take a look at the nginx sample: https://github.com/ohmyform/ohmyform/tree/master/examples/docker_nginx

-> and then you could work with the default.conf file to see what needs to be proxied in terms of containers. (as caddy is also a reverse proxy as far as I can see)

**Reply by spencerflagg** [reply]
Good point - thanks!

As it turns out, I'd already come up with the correct solution but apparently forgot to restart the caddy container after the config change. :man_facepalming: 

Thanks again, I'll add my working config below, and try to contribute it to the project as well.

**docker-compose.yml**
```
version: "3.9"

networks:
        web:
                external: true
        internal:
                external: false
                driver: bridge

services:
        caddy:
                container_name: caddy
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
                        - /data/caddy/data:/data # Optional
                        - /data/caddy/config:/config # Optional
                networks:
                        - web
                        - internal
        ohmyform:
                container_name: ohmyform
                image: ohmyform/ohmyform
                volumes:
                  - "./data:/data"
                environment:
                  CREATE_ADMIN: "TRUE"
                  ADMIN_EMAIL: admin@local.host
                  ADMIN_USERNAME: admin
                  ADMIN_PASSWORD: admin
                  DATABASE_DRIVER: sqlite
                  DATABASE_URL: "sqlite:///data/data.sqlite"
                  MAILER_URI: smtp://local.host
                  LOGIN_NOTE: "Either login with admin:admin or create your own account to test OhMyForm"
                restart: unless-stopped
                networks:
                        - internal
```

**Caddyfile**
```
mywebsite.com {
        reverse_proxy ohmyform:3000
}
```

**Reply by spencerflagg** [reply]
https://github.com/ohmyform/ohmyform/pull/167

**Comment by spencerflagg** [comment, marked as answer]
As it turns out, I'd already come up with the correct solution but apparently forgot to restart the caddy container after the config change. :man_facepalming: 

Thanks again, I'll add my working config below, and try to contribute it to the project as well.

**docker-compose.yml**
```
version: "3.9"

networks:
        web:
                external: true
        internal:
                external: false
                driver: bridge

services:
        caddy:
                container_name: caddy
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
                        - /data/caddy/data:/data # Optional
                        - /data/caddy/config:/config # Optional
                networks:
                        - web
                        - internal
        ohmyform:
                container_name: ohmyform
                image: ohmyform/ohmyform
                volumes:
                  - "./data:/data"
                environment:
                  CREATE_ADMIN: "TRUE"
                  ADMIN_EMAIL: admin@local.host
                  ADMIN_USERNAME: admin
                  ADMIN_PASSWORD: admin
                  DATABASE_DRIVER: sqlite
                  DATABASE_URL: "sqlite:///data/data.sqlite"
                  MAILER_URI: smtp://local.host
                  LOGIN_NOTE: "Either login with admin:admin or create your own account to test OhMyForm"
                restart: unless-stopped
                networks:
                        - internal
```

**Caddyfile**
```
mywebsite.com {
        reverse_proxy ohmyform:3000
}
```
