### ISSUE TITLE
Some environment variables do not work with the combined Docker image

### ISSUE THREAD

**Issue by Tmpod** [ohmyform/ohmyform#131]
#### What's this issue about?

Upon trying out the combined Docker image (and having a little chat on Discord with wodka) I noticed that at least `HIDE_CONTRIB` and `SIGNUP_DISABLED` does not appear to do anything - the "Fork me" banner is still there and the login/signup buttons still appear (as shown in the picture below).

It is not a problem of environment variables not reaching the application in some way, since the admin user related stuff works perfectly fine.

![image](https://user-images.githubusercontent.com/35771816/116457187-ff60f780-a85a-11eb-8b01-6de108f5498f.png)

#### Expected behavior

The "Fork & Support" banner and login/signup buttons should disappear upon setting the environment variables.

#### Actual behavior

Those elements are still being displayed.

#### Environment

`neofetch`
![image](https://user-images.githubusercontent.com/35771816/116457704-a2197600-a85b-11eb-9228-feae0d8d0888.png)

`docker --version`
```
Docker version 19.03.13, build 4484c46d9d
```

`docker-compose --version`
```
docker-compose version 1.27.4, build 40524192
```

Using [`ohmyform/ohmyform:0.9`](https://hub.docker.com/layers/ohmyform/ohmyform/0.9/images/sha256-c42393982d4c909827b9079a55c07678942b2c7e6b4d1c4b0481ce3dfc4e1bc8) as the Docker image.  
Here's the full compose file:
```yml
version: "3"

services:
  ohmyform:
    image: ohmyform/ohmyform:0.9
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL: ...
      ADMIN_USERNAME: ...
      ADMIN_PASSWORD: ...
      MONGODB_URI: mongodb://mongo/ohmyform
      MAILER_URI: smtp://local.host
      PORT: 5000
      HIDE_CONTRIB: "TRUE"
      SIGNUP_DISABLED: "TRUE"
    links:
      - mongo
#    ports:
#      - "8080:5000"
    depends_on:
      - mongo
    networks:
      - db
      - global_proxy

  mongo:
    image: mongo:4.0
    volumes:
      - "./data/mongo:/data/db"
    networks:
      - db

# I have a container running Caddy that proxies a lot of stuff on my VPS through a global network.
networks: 
  db:
  global_proxy:
    external:
      name: caddy_global_cadd
```
