### ISSUE TITLE
{statusCode: 404, message: "Cannot POST /", error: "Not Found"}

### ISSUE THREAD

**Issue by Jaxmetalmax** [ohmyform/ohmyform#134]
#### What's this issue about?

Running ohmyform via docker with docker-compose, it shows a message that says "{statusCode: 404, message: "Cannot POST /", error: "Not Found"}" when loading login page, but the API is running and responds with:

```
OhMyForm API endpoint


visit us at ohmyform.com
```

#### Expected behavior
login with the admin admin user and password

#### Actual behavior
when login shows invalid username or password

#### Environment
docker-compose version 1.23.2, build 1110ad01
Docker version 20.10.3, build 48d30b5
O.S: ubuntu 18.04

docker-compose.yml file:

```
version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres:10-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ohmyform
  ui:
    image: ohmyform/ui
    environment:
      API_HOST: https://form.oursite.com/graphql
      PORT: 5000
    ports:
      - "8080:5000"
  api:
    image: ohmyform/api
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL: admin@local.host
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      DATABASE_DRIVER: postgres
      DATABASE_URL: postgresql://root:root@db:5432/ohmyform
      MAILER_URI: smtp://local.host
      REDIS_URL: redis://redis
      PORT: 5000
    links:
      - db
      - redis
    ports:
      - "8090:5000"
    depends_on:
      - db
      - redis

volumes:
  pg_data:
```

nginx conf:

```
upstream apiohmyform {
      server 127.0.0.1:8090;
}

upstream webohmyform {
      server 127.0.0.1:8080;
}


server {
        server_name form.oursite.com;

        error_log /var/log/nginx/ohmyform_error.log;

        location / {
            proxy_pass http://webohmyform;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

        location /graphql {
            proxy_pass http://apiohmyform/;
            proxy_set_header Host $host;
            proxy_redirect off;
        }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/form.oursite.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/form.oursite.com/privkey.pem; # managed by Certbot

}


server {
        listen 80;
        server_name form.oursite.com;
        return 301 https://$host$request_uri;
}
```

Request headers:

```
POST /graphql HTTP/1.1
Host: form.oursite.com
Connection: keep-alive
Content-Length: 345
accept: */*
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
content-type: application/json
Sec-GPC: 1
Origin: https://form.oursite.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://form.oursite.com/login
Accept-Encoding: gzip, deflate, br
Accept-Language: es-419,es;q=0.9
```

request payload:

```
{"operationName":"settings","variables":{},"query":"query settings {\n  disabledSignUp: getSetting(key: \"SIGNUP_DISABLED\") {\n    value: isTrue\n    __typename\n  }\n  loginNote: getSetting(key: \"LOGIN_NOTE\") {\n    value\n    __typename\n  }\n  hideContrib: getSetting(key: \"HIDE_CONTRIB\") {\n    value: isTrue\n    __typename\n  }\n}\n"} 
```
