### ISSUE TITLE
MariaDB/MySQL support

### ISSUE THREAD

**Issue by OoLunar** [ohmyform/ohmyform#143]
#### What's this issue about?
Proper support for MariaDB/MySQL

#### Expected behavior
Connecting successfully and tables created

#### Actual behavior
Connected successfully with the following uri: `DATABASE_URL: "mysql://ohmyform:redacted@mariadb/ohmyform"`
Error:
```json
{
  "level": 50,
  "time": 1630993421116,
  "pid": 82,
  "hostname": "f2d7f3dd3939",
  "context": "TypeOrmModule",
  "trace": "QueryFailedError: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '\"form_field_logic\" (\"id\" SERIAL NOT NULL, \"formula\" character varying NOT NUL...' at line 1\n    at new QueryFailedError (/usr/src/api/node_modules/typeorm/error/QueryFailedError.js:12:28)\n    at Query.onResult (/usr/src/api/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:217:45)\n    at Query.execute (/usr/src/api/node_modules/mysql2/lib/commands/command.js:30:14)\n    at PoolConnection.handlePacket (/usr/src/api/node_modules/mysql2/lib/connection.js:425:32)\n    at PacketParser.onPacket (/usr/src/api/node_modules/mysql2/lib/connection.js:75:12)\n    at PacketParser.executeStart (/usr/src/api/node_modules/mysql2/lib/packet_parser.js:75:16)\n    at Socket.<anonymous> (/usr/src/api/node_modules/mysql2/lib/connection.js:82:25)\n    at Socket.emit (events.js:315:20)\n    at addChunk (internal/streams/readable.js:309:12)\n    at readableAddChunk (internal/streams/readable.js:284:9)",
  "msg": "Unable to connect to the database (ohmyform). Retrying (1)..."
}
```

#### Steps to reproduce
Create a docker-compose.yml like such:
```yml
version: '3.9'

services:
  ohmyform:
    image: ohmyform/ohmyform
    volumes:
    - "./data:/data"
    environment:
      CREATE_ADMIN: "TRUE"
      ADMIN_EMAIL: admin@redacted
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: redacted
      DATABASE_DRIVER: mariadb
      DATABASE_URL: "mysql://ohmyform:redacted@mariadb/ohmyform"
      MAILER_URI: "smtp://noreply:redacted@smtp"
      LOGIN_NOTE: "You may need to create an account before logging in. Check for emails from noreply@redacted"
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=redacted
    volumes:
      - ./database:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/mariadb.cnf
    restart: always
```

#### Environment
Docker: Docker version 20.10.8, build 3967b7d
OS: CentOS 7

# Misc
Unsure if MySQL is even supported. An error didn't throw when parsing the `DATABASE_URL` variable, so I'm assuming yes.
