### ISSUE TITLE
Unable to get mail sending to work

### ISSUE THREAD

**Issue by networkException** [ohmyform/ohmyform#145]
#### What's this issue about?

After setting up a ohmyform and configuring a form that confirms the submission using an email, no email gets sent on submitting.

#### Expected behavior

An email should be sent to the address entered in the form

#### Actual behavior

No email gets sent

#### Steps to reproduce

Setup a docker enviornment (I initially used podman but tested it on both) using the following compose file:

```yml
version: "3"

services:
    database:
        image: mongo
        container_name: forms-database
        restart: unless-stopped
        volumes:
            - ./data/mongo:/data/db

    mail:
        image: mailhog/mailhog
        container_name: forms-mail
        restart: unless-stopped

    ohmyform:
        image: ohmyform/ohmyform:0.9.9
        container_name: forms-ohmyform
        restart: unless-stopped
        depends_on:
            - database
            - mail
        volumes:
            - ./data:/data
        environment:
           CREATE_ADMIN: "TRUE"
            ADMIN_EMAIL: admin@example.com
            ADMIN_USERNAME: user
            ADMIN_PASSWORD: password
            SIGNUP_DISABLED: "TRUE"
            HIDE_CONTRIB: "TRUE"
            MONGODB_URI: mongodb://database/ohmyform
            MAILER_URI: "smtp://mail:1025"
            MAILER_FROM: "Forms <no-reply@example.com>"
            PORT: 3000
        ports:
            - 3000:3000
```

#### Environment

Tested on Ubuntu 20.04.3 LTS with Docker version 20.10.8 and podman version 3.3.1
