### ISSUE TITLE
Question about docker usage with Caddy

### ISSUE THREAD

**Issue by spencerflagg** [ohmyform/ohmyform#165]
#### What's this issue about?

_(bit of a Docker newb - sorry. I hope this is the right place to post questions. I've been spinning my wheels on this, trying different permutations none of which have worked, and figured I'd reach out to the community for insight.)_

I'm trying to incorporate OhMyForm into an existing `docker-compose.yml` that uses Caddy and docker networks.

Any suggestions for how I can adjust OhMyForm's compose for integrating with the below would be greatly appreciated.

Thanks in advance!

**docker-compose.yml**
```
version: "3.9"

networks:
        web:
                external: true
        internal:
                external: false
                driver: bridge

services:
        caddy:
                container_name: caddy
                image: caddy:2-alpine
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
                        - /data/caddy/data:/data # Optional
                        - /data/caddy/config:/config # Optional
                networks:
                        - web
                        - internal
        ghost-alt:
                container_name: ghost-alt
                image: ghost:4-alpine
                restart: unless-stopped
                environment:
                        - url=https://mydomain.com # Change to your domain
                volumes:
                        - /data/ghost-alt:/var/lib/ghost/content
                networks:
                        - internal
```

**Caddyfile**
```
mydomain.com {
    reverse_proxy ghost-alt:2368
}
```
