### ISSUE TITLE
"username / password are invalid" when using any DB other than SQLite

### ISSUE THREAD

**Issue by biggt** [ohmyform/ohmyform#189]
#### What's this issue about?
If I have any database configured other than using SQLite and try to login using the configured admin username and password and try to sign in, it shows "username / password are invalid". I have set multiple usernames, multiple passwords, easy, hard... they all result in the same error message. 

#### Expected behavior
I expect to be able to sign in properly with a configured admin username and password. 

#### Actual behavior
I receive the error "username / password are invalid".

#### Steps to reproduce
Configure docker-compose.yml with either postgres or mariadb setup, bring up the app, try to login with the configured username and password. 

#### Environment
Ubuntu 22.04 LTS
```
`docker version` 
Client:
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        20.10.12-0ubuntu4
 Built:             Mon Mar  7 17:10:06 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       20.10.12-0ubuntu4
  Built:            Mon Mar  7 15:57:50 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.9-0ubuntu3
  GitCommit:
 runc:
  Version:          1.1.0-0ubuntu1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:
```

Docker image versions: 
ohmyform/api                           latest            8b85df65c9d6   4 months ago    212MB
ohmyform/ohmyform                      latest            1947e088590e   4 months ago    945MB
ohmyform/ui                            latest            54ac104f7fe4   4 months ago    800MB
postgres                               10-alpine         d7023df56cb7   7 days ago      79.1MB
node                                   16-alpine         b0cbdedc1b9d   7 days ago      112MB
redis                                  latest            3edbb69f9a49   7 days ago      117MB
mariadb                                latest            ea81af801379   7 weeks ago     383MB

Code: 

```
version: "3"
services:
  redis:
    image: redis

#  db:
#    image: postgres:10-alpine
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: adm1n
#      POSTGRES_PASSWORD: r00tpassw0rd
#      POSTGRES_DB: ohmyform
#    restart: unless-stopped
  maria:
    image: mariadb
    volumes:
      - ./maria_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00tpassw0rd
      MYSQL_DATABASE: ohmyform
    ports:
      - "3306:3306"


  ui:
    image: ohmyform/ui
    environment:
      #ENDPOINT: http://localhost:8090/graphql
      ENDPOINT: http://api:8090/graphql
      SERVER_ENDPOINT: http://api:5000/graphql
      PORT: 5000
    ports:
      - "8086:5000"
    restart: unless-stopped
  api:
    image: ohmyform/api
    environment:
      CREATE_ADMIN: "true"
#      ADMIN_EMAIL: admin@localhost.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: adminpassword
#      DATABASE_DRIVER: postgres
      DATABASE_DRIVER: mariadb
#      DATABASE_URL: postgresql://adm1n:r00tpassw0rd@db:5432/ohmyform
      DATABASE_URL: mariadb://root:r00tpassw0rd@maria:3306/ohmyform
      REDIS_URL: redis://redis:6379
      PORT: 5000
      SIGNUP_DISABLED: "true"
      DEFAULT_ROLE: "user"
      HIDE_CONTRIB: "true"
    links:
#      - db
      - maria
      - redis
    ports:
      - "8090:5000"
    depends_on:
 #     - db
      - maria
      - redis
    restart: unless-stopped
```
