### ISSUE TITLE
[error] Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by karser** [ohmyform/ohmyform#34]
Using docker `ohmyform/ohmyform:0.2.3`

Steps to reproduce:

1. Create new survey with one text question
2. Go to Form Settings

![image](https://user-images.githubusercontent.com/1675033/64105882-bb64d900-cd7f-11e9-805c-e167bf6ac030.png)

**Comment by wodka** [comment]
Yes, this one is annoying - it works when you refresh the page once after creating the form

**Comment by nimrodcoder** [comment]
Hey, I'd like to help out with this one. Can  you tell me what i'd need to do to setup the project locally?

**Comment by Leopere** [comment]
Just like the Hitch Hikers Guide "the answer to life the universe and everything" the answer is #42 we should work on helping you get a dev instance available while also monitoring this issue for Q&A as to what's needed to get you to a point of a working development environment.  

So far the basic instructions exist within the [Dockerfile](https://github.com/ohmyform/ohmyform/blob/master/Dockerfile) Prerequisites are established in [this section](https://github.com/ohmyform/ohmyform/blob/master/Dockerfile#L5-L9) however if you're struggling even after `git clone`'ing your own fork of this repository and then getting the node commands run at the [end of the Dockerfile](https://github.com/ohmyform/ohmyform/blob/master/Dockerfile#L47-L52) where what is on [line 52](https://github.com/ohmyform/ohmyform/blob/master/Dockerfile#L52) the command would translate to `node server.js` when run in the console.  

The preparation for the installation is basically as follows. 
```BASH 
npm install --only=production \
    && bower install --allow-root -f \
    && grunt build` 
```

**Comment by Leopere** [comment]
You will need to have a MongoDB instance installed and hopefully a SMTP server available to test on.  

Otherwise I suppose there is also the hopefully easier way where you just use `docker-compose build && docker-compose up` after uncommenting [this line](https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml#L12) and commenting out [this line](https://github.com/ohmyform/ohmyform/blob/master/docker-compose.yml#L11) 

What that would look like is specifically as this:
```YAML
## TODO: add a compose examples directory with various deployment options.
version: "3"
services:
  redis:
    image: redis
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data"
  ohmyform:
    # image: ohmyform/ohmyform
   build: .
    #volumes:
    #  - ".:/opt/app"
    environment:
      CREATE_ADMIN: "TRUE"
      SOCKET_URL: 'localhost:5000'
      SOCKET_PORT: "5000"
      SOCKET_PORT_EXTERN_VISIBLE: "TRUE"
      MONGODB_URI: mongodb://mongo/ohmyform
      REDIS_URL: redis://redis
      MAILER_SMTP_HOST: mail
      MAILER_SMTP_PORT: 1025
    # command: grunt dev # override command to have livereloading on file change
    links:
      - mongo
      - redis
      - mail
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mail:
    image: mailhog/mailhog
    ports:
      - "5050:8025"
  mongoexpress:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "5051:8081"
    links:
      - mongo
    depends_on:
      - mongo
```
