### ISSUE TITLE
[docker] websocket connection doesn't work

### ISSUE THREAD

**Issue by karser** [ohmyform/ohmyform#36]
Steps to reproduce:
- Go to design tab and try to change any field. Open console and see the error
```
WebSocket connection to 'wss://ohmyform.mydomain.com:5000/socket.io/?EIO=3&transport=websocket' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR
```

I use traefik, here is my docker setup:
```
version: "3"

services:
  redis:
    image: redis
    networks:
      - backend

  mongo:
    image: mongo
    volumes:
      - "${STORAGE}/mongo:/data"
    networks:
      - backend

  ohmyform:
    image: ohmyform/ohmyform:0.2.3
    #build: .
    #volumes:
    #  - ".:/opt/app"
    environment:
      CREATE_ADMIN: "TRUE"
      SOCKET_URL: 'localhost:5000'
      SOCKET_PORT: "5000"
      SOCKET_PORT_EXTERN_VISIBLE: "TRUE"
      MONGODB_URI: mongodb://mongo/ohmyform
      REDIS_URL: redis://redis
      MAILER_SMTP_HOST: mail
      MAILER_SMTP_PORT: 1025
    # command: grunt dev # override command to have livereloading on file change
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - backend
      - webproxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ohmyform"
      - "traefik.frontend.rule=Host:ohmyform.mydomain.com"
      - "traefik.frontend.priority=20"
      - "traefik.port=5000"
      - "traefik.docker.network=webproxy"
      - "traefik.webservice.frontend.entryPoints=http,https,ws,wss"

  mail:
    image: mailhog/mailhog
    ports:
      - "5050:8025"
    networks:
      - backend

networks:
  backend:
  webproxy:
    external: true
```
